Implementation smell,Namespace,Class,File,Method,Description
Long Identifier,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02A,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02A.ConditionalExceptionCatch.cs,ChapterMain,The length of the parameter ThrowInvalidOperationException is 30.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02.CatchingDifferentExceptionTypes.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02.CatchingDifferentExceptionTypes.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02.CatchingDifferentExceptionTypes.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02.CatchingDifferentExceptionTypes.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02.CatchingDifferentExceptionTypes.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_03,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.03.UsingExceptionDispatchInfoToRethrowException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_03,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.03.UsingExceptionDispatchInfoToRethrowException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_03,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.03.UsingExceptionDispatchInfoToRethrowException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_03,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.03.UsingExceptionDispatchInfoToRethrowException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_03,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.03.UsingExceptionDispatchInfoToRethrowException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_04,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.04.CreatingACustomException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_04,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.04.CreatingACustomException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_04,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.04.CreatingACustomException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_04,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.04.CreatingACustomException.cs,ChapterMain,The method has an empty catch block.
Empty Catch Block,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_04,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.04.CreatingACustomException.cs,ChapterMain,The method has an empty catch block.
Magic Number,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02.CatchingDifferentExceptionTypes.cs,ChapterMain,The following statement contains a magic number: try              {                  throw new Win32Exception(42);                  //TextNumberParser.Parse("negative forty-two");                  // ...                  throw new InvalidOperationException(                      "Arbitrary exception");                  // ...              }              catch(Win32Exception exception)                   when(args.Length == exception.NativeErrorCode)              {                }              catch(NullReferenceException exception)              {                  // Handle NullReferenceException              }              catch(ArgumentException exception)              {                  // Handle ArgumentException              }              catch(InvalidOperationException exception)              {                  // Handle ApplicationException              }              catch(Exception exception)              {                  // Handle Exception              }              finally              {                  // Handle any cleanup code here as it runs                  // regardless of whether there is an exception              }
Magic Number,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02A,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02A.ConditionalExceptionCatch.cs,ChapterMain,The following statement contains a magic number: try              {                  List<string> locations = new List<string>();                  try                  {                      // ...                          throw new System.ComponentModel.Win32Exception(42' "Custom error");                  }                  catch (System.ComponentModel.Win32Exception exception)                      when (exception.NativeErrorCode == 42)                  {                      bool exceptionHandled = false;                        Console.WriteLine("Inside Win32Exception catch block");                        if (!exceptionHandled)                      {                          throw;                      }                  }              }              catch (NullReferenceException exception)              {                  Console.WriteLine(exception);              }
Magic Number,AddisonWesley.Michaelis.EssentialCSharp.Chapter10.Listing10_02A,Program,C:\repos\IntelliTect_EssentialCSharp\src\Chapter10\Listing10.02A.ConditionalExceptionCatch.cs,ChapterMain,The following statement contains a magic number: try              {                  List<string> locations = new List<string>();                  try                  {                      // ...                          throw new System.ComponentModel.Win32Exception(42' "Custom error");                  }                  catch (System.ComponentModel.Win32Exception exception)                      when (exception.NativeErrorCode == 42)                  {                      bool exceptionHandled = false;                        Console.WriteLine("Inside Win32Exception catch block");                        if (!exceptionHandled)                      {                          throw;                      }                  }              }              catch (NullReferenceException exception)              {                  Console.WriteLine(exception);              }
